using System;
using System.IO;
using System.Text;
using AdriKat.Toolkit.Utility;
using AdriKat.Toolkit.Utility.Extensions;
using UnityEditor;
using UnityEngine;

// using AdriKat.Toolkit.Settings;

namespace AdriKat.Toolkit.Audio
{
    public static class AudioIDGenerator
    {
        private const string CLASS_FILENAME = "AudioIDs.cs";
        
        private static string lastScriptLocation;
        
        [MenuItem("Toolkit/Audio/Refresh AudioIDs Script")]
        public static void GenerateAudioIDClass()
        {
            AudioSettings audioSettings = AudioSettingsProvider.GetOrCreateSettings();
            
            // Load the database first from the settings, or from the 'resources' folder.
            var db = audioSettings.DefaultAudioDatabase ?
                audioSettings.DefaultAudioDatabase :
                Resources.Load<AudioDatabase>("AudioDatabase");
            
            if (db == null)
            {
                Debug.LogWarning("Missing AudioDatabase reference in Audio Settings, and no database has been found in the Resources folder (Create->Audio->AudioDatabase). Ensure its name is exactly 'AudioDatabase.asset'.");
                return;
            }
            
            if (db.allSounds.IsNullOrEmpty())
            {
                Debug.Log("The AudioDatabase is empty. Nothing to generate.");
                return;
            }

            var sb = new StringBuilder();
            sb.AppendLine("//// ***** AdriKat *****");
            sb.AppendLine("//// THIS CODE HAS BEEN AUTO GENERATED BY THE CLASS AudioIDGenerator.");
            sb.AppendLine("//// ANY MODIFICATIONS WILL GET OVERWRITTEN NEXT TIME THE GENERATOR IS RE-RUN.\n");
            sb.AppendLine("namespace AdriKat.Toolkit.Audio\n{");
            sb.AppendLine("\tpublic static class AudioIDs");
            sb.AppendLine("\t{");
            
            foreach (var sound in db.allSounds)
            {
                if (sound == null || sound.id.IsNullOrEmpty()) continue;
                string cleanName = sound.id.Replace(" ", "_");
                sb.AppendLine($"\t\tpublic const string {cleanName} = \"{sound.id}\";");
            }

            sb.AppendLine("\t}\n}");

            string path;

            var audioIDType = Type.GetType("AdriKat.Toolkit.Audio.AudioIDs");
            if (audioIDType == null)
            {
                // The script doesn't exist at all. Use the default path to create it.
                path = $"{audioSettings.AudioIDClassFolder}/{CLASS_FILENAME}";
                Debug.Log($"Generating {CLASS_FILENAME} at '{path}'...");
            }
            else if (lastScriptLocation != null && File.Exists(lastScriptLocation))
            {
                // The previous file cache is "valid". Let's suppose it's not another file with the same name...
                path = lastScriptLocation;
                Debug.Log($"Updating {CLASS_FILENAME} at '{path}'...");
            }
            else
            {
                // Let's look for it ourselves (expensive).
                path = EditorUtils.FindScriptFilePath(audioIDType);
                Debug.Log($"Updating {CLASS_FILENAME} at '{path}'...");
            }
                
            lastScriptLocation = path;
            
            EditorUtils.CreateFoldersRecursively(Path.GetDirectoryName(path));
            File.WriteAllText(path, sb.ToString());

            if (audioSettings.RefreshAssetsAfterGeneration)
            {
                AssetDatabase.Refresh();
            }

            Debug.Log("AudioIDs.cs is now up to date.");
        }
    }
}
