using System;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using AdriKat.Toolkit.Utility;
using AdriKat.Toolkit.Utility.Extensions;
using UnityEditor;
using UnityEngine;

// using AdriKat.Toolkit.Settings;

namespace AdriKat.Toolkit.Audio
{
    public static class AudioIDGenerator
    {
        public const string AUDIO_DATABASE_DEFAULT_PATH = "Assets/Audio/AudioDatabase.asset";
        private const string FILE_REPLACE_PATTERN = "[ -#%!~&+']";

        private static string _lastScriptLocation;
        
        [MenuItem("Toolkit/Audio/Refresh AudioIDs Script")]
        public static void GenerateAudioIDClass()
        {
            AudioSettings audioSettings = AudioSettingsProvider.GetOrCreateSettings();
            
            // Load the database first from the settings, or from the 'resources' folder.
            var db = audioSettings.DefaultAudioDatabase ?
                audioSettings.DefaultAudioDatabase :
                AssetDatabase.LoadAssetAtPath<AudioDatabase>(AUDIO_DATABASE_DEFAULT_PATH);
            
            if (db == null)
            {
                Debug.LogWarning("No AudioDatabase is referenced in AudioSettings, and no database has been found in the Audio folder (Create->Audio->AudioDatabase). Ensure its name is exactly 'AudioDatabase.asset'.");
                return;
            }
            
            if (db.allSounds.IsNullOrEmpty())
            {
                Debug.Log("The AudioDatabase is empty. Nothing to generate.");
                return;
            }

            var sb = new StringBuilder();
            sb.AppendLine("//// ***** AdriKat *****");
            sb.AppendLine("//// THIS CODE HAS BEEN AUTO GENERATED BY THE CLASS AudioIDGenerator.");
            sb.AppendLine("//// ANY MODIFICATIONS WILL GET OVERWRITTEN NEXT TIME THE GENERATOR IS RE-RUN.\n");
            sb.AppendLine("namespace AdriKat.Toolkit.Audio\n{");
            sb.Append("\tpublic static class "); sb.Append(audioSettings.AudioIDClassName);
            sb.AppendLine("\t{");
            
            foreach (var sound in db.allSounds)
            {
                if (sound == null || sound.id.IsNullOrEmpty()) continue;
                Regex pattern = new Regex(FILE_REPLACE_PATTERN);
                string cleanName = pattern.Replace(sound.id, "_");
                sb.AppendLine($"\t\tpublic const string {cleanName} = \"{sound.id}\";");
            }

            sb.AppendLine("\t}\n}");

            string path;
            string audioSettingsTypeName = "AdriKat.Toolkit.Audio." + audioSettings.AudioIDClassName;
            
            var audioIDType = Type.GetType(audioSettingsTypeName);
            if (audioIDType == null)
            {
                // The script doesn't exist at all. Use the default path to create it.
                path = $"{audioSettings.AudioIDClassFolder}/{audioSettings.AudioIDClassName}.cs";
                Debug.Log($"Generating {audioSettings.AudioIDClassName}.cs at '{path}'...");

                if (_lastScriptLocation != null && File.Exists(_lastScriptLocation))
                {
                    string message = $"The previous script location was '{_lastScriptLocation}', but the type '{audioSettingsTypeName}' doesn't exist anymore. This happens when the typename or namespace has been changed.";
                    Debug.LogWarning(message);
                    message += $"\n\nWould you like to delete it?";
                    bool delete = EditorUtility.DisplayDialog("AudioIDs Script Generation", message, "Delete Old Script", "Keep Old Script");
                    
                    if (delete)
                    {
                        if (File.Exists(_lastScriptLocation))
                        {
                            File.Delete(_lastScriptLocation);
                            Debug.Log($"Deleted old script at '{_lastScriptLocation}'.");
                        }
                        else
                        {
                            EditorUtility.DisplayDialog("AudioIDs Script Generation", "But the script was already gone.", "Ok");
                        }
                    }
                }
            }
            else if (_lastScriptLocation != null && File.Exists(_lastScriptLocation))
            {
                // The previous file cache is "valid". Let's suppose it's not another file with the same name...
                path = _lastScriptLocation;
                Debug.Log($"Updating {audioSettings.AudioIDClassName}.cs at '{path}'...");
            }
            else
            {
                // Let's look for it ourselves (expensive).
                path = EditorUtils.FindScriptFilePath(audioIDType);
                Debug.Log($"Updating {audioSettings.AudioIDClassName}.cs at '{path}'...");
            }
                
            _lastScriptLocation = path;
            
            EditorUtils.CreateFoldersRecursively(Path.GetDirectoryName(path));
            File.WriteAllText(path, sb.ToString());

            if (audioSettings.RecompileAfterGeneratingAudioIDs)
            {
                AssetDatabase.Refresh();
            }

            Debug.Log(audioSettings.AudioIDClassName + ".cs is now up to date.", EditorUtils.GetPingableFileReference(path));
        }
    }
}
